### ISSUE TITLE
No such file or directory: '.../rconf.tx'

### ISSUE THREAD

**Issue by GeneralBison** [igordejanovic/remark-compose#1]
When I try building I get the following error:
```IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/remarkcompose/rconf.tx```

I installed via pip.

This tool is exactly what I'm looking for by the way, thank you for building it.

**Comment by igordejanovic** [comment]
You are welcome!
Try it now. Should be fine.

**Comment by GeneralBison** [comment]
Builds fine now! Thanks!
